[[inputs.snmp]]
  agents = ["udp://172.10.10.10:161","udp://172.10.10.11:161","udp://172.10.10.12:161","udp://172.10.10.13:161"]
  version = 2
  community = "public"
  name = "Lab"
  agent_host_tag = "source"
  
  # Timeout e intervalo entre as coletas
  timeout = "10s"
  interval = "60s"

# Netflow v5, Netflow v9 and IPFIX collector
[[inputs.netflow]]
  ## Address to listen for netflow,ipfix or sflow packets.
  ##   example: service_address = "udp://:2055"
  ##            service_address = "udp4://:2055"
  ##            service_address = "udp6://:2055"
  service_address = "udp://:2055"

  ## Set the size of the operating system's receive buffer.
  ##   example: read_buffer_size = "64KiB"
  ## Uses the system's default if not set.
  # read_buffer_size = ""
  # Hostname do dispositivo
    [[inputs.snmp.field]]
      name = "hostname"
      oid = "RFC1213-MIB::sysName.0"
      is_tag = true
  
    # Uptime do dispositivo
    [[inputs.snmp.field]]
      name = "uptime"
      oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"
  
    # IP-MIB: Coleta de endereços IP
    [[inputs.snmp.field]]
      name = "interface_ip"
      oid = "IP-MIB::ipAdEntAddr"
    
    [[inputs.snmp.field]]
      name = "interface_netmask"
      oid = "IP-MIB::ipAdEntNetMask"
    
    [[inputs.snmp.field]]
      name = "interface_index"
      oid = "IP-MIB::ipAdEntIfIndex"
  
    # IF-MIB::ifTable - Contadores de tráfego, erros e descartes
    [[inputs.snmp.table]]
      name = "interface"
      inherit_tags = ["hostname"]
      oid = "IF-MIB::ifTable"
  
      [[inputs.snmp.table.field]]
        name = "ifDescr"
        oid = "IF-MIB::ifDescr"
        is_tag = true
  
    # IF-MIB::ifXTable - Contadores de alta capacidade
    [[inputs.snmp.table]]
      name = "interface"
      inherit_tags = ["hostname"]
      oid = "IF-MIB::ifXTable"
  
      [[inputs.snmp.table.field]]
        name = "ifDescr"
        oid = "IF-MIB::ifDescr"
        is_tag = true
  
    # EtherLike-MIB::dot3StatsTable - Informações detalhadas de erros Ethernet
    [[inputs.snmp.table]]
      name = "interface"
      inherit_tags = ["hostname"]
      oid = "EtherLike-MIB::dot3StatsTable"
  
      [[inputs.snmp.table.field]]
        name = "ifDescr"
        oid = "IF-MIB::ifDescr"
        is_tag = true

[[processors.converter]]
  [processors.converter.fields]
    tag = ["protocol", "src", "src_port", "dst", "dst_port"]
  ## Protocol version to use for decoding.
  ## Available options are
  ##   "ipfix"      -- IPFIX / Netflow v10 protocol (also works for Netflow v9)
  ##   "netflow v5" -- Netflow v5 protocol
  ##   "netflow v9" -- Netflow v9 protocol (also works for IPFIX)
  ##   "sflow v5"   -- sFlow v5 protocol
  # protocol = "ipfix"

  ## Private Enterprise Numbers (PEN) mappings for decoding
  ## This option allows to specify vendor-specific mapping files to use during
  ## decoding.
  # private_enterprise_number_files = []

  ## Log incoming packets for tracing issues
  # log_level = "trace"

[[inputs.syslog]]
  server = "tcp://0.0.0.0:514"

[[outputs.influxdb]]
  ## Configuração do InfluxDB (ou outro destino de saída)
  urls = ["http://influxdb:8086"]
  skip_database_creation = true
  database = "telemetry"
  password = "admin"
 
